name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Build the Docker image once
      - name: Build Docker image
        run: |
          docker build -t docker-node-app .

      # Step 4: Push to Docker Hub
      - name: Push to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker tag docker-node-app $DOCKER_USERNAME/docker-node-app:latest
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push $DOCKER_USERNAME/docker-node-app:latest

      # Step 5: Push to AWS ECR
      - name: Push to AWS ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 149790123077.dkr.ecr.$AWS_REGION.amazonaws.com
          docker tag docker-node-app 149790123077.dkr.ecr.$AWS_REGION.amazonaws.com/docker-node-app:latest
          docker push 149790123077.dkr.ecr.$AWS_REGION.amazonaws.com/docker-node-app:latest

      # Step 6: Push to GCP Artifact Registry
      - name: Push to GCP Artifact Registry
        env:
          GCP_PROJECT_ID: project-525a47ad-8a94-41ce-85d
          GCP_REGION: us-central1
          GCP_REPOSITORY: docker-node-app
          GCP_SA_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        run: |
          echo $GCP_SA_KEY > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud auth configure-docker $GCP_REGION-docker.pkg.dev
          docker tag docker-node-app $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$GCP_REPOSITORY/docker-node-app:latest
          docker push $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$GCP_REPOSITORY/docker-node-app:latest
