name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ---------------- Checkout code ----------------
      - uses: actions/checkout@v2

      # ---------------- Set up Docker Buildx ----------------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # ---------------- Build Docker image ----------------
      - name: Build Docker image
        run: docker build -t docker-node-app .

      # ---------------- Push to Docker Hub ----------------
      - name: Push to Docker Hub
        run: |
          docker tag docker-node-app:latest bigoronaa/docker-node-app:latest
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push bigoronaa/docker-node-app:latest

      # ---------------- Push to AWS ECR ----------------
      - name: Push to AWS ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          # Log in to AWS ECR
          aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 149790123077.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
          
          # Tag the Docker image for ECR
          docker tag docker-node-app:latest 149790123077.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/docker-node-app:latest
          
          # Push the image to ECR
          docker push 149790123077.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/docker-node-app:latest

     