name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ---------------- Checkout code ----------------
      - uses: actions/checkout@v2

      # ---------------- Set up Docker Buildx ----------------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # ---------------- Build and push to Docker Hub ----------------
      - name: Build and push to Docker Hub
        run: |
          docker build -t bigoronaa/docker-node-app .
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push bigoronaa/docker-node-app

      # ---------------- Build and push to AWS ECR ----------------
      - name: Build and push to AWS ECR
        run: |
          docker tag docker-node-app 149790123077.dkr.ecr.us-east-1.amazonaws.com/docker-node-app
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 149790123077.dkr.ecr.us-east-1.amazonaws.com
          docker push 149790123077.dkr.ecr.us-east-1.amazonaws.com/docker-node-app

      # ---------------- Build and push to GCP Artifact Registry ----------------
      - name: Build and push to GCP Artifact Registry
        run: |
          docker tag docker-node-app us-central1-docker.pkg.dev/project-525a47ad-8a94-41ce-85d/docker-node-app/docker-node-app
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker push us-central1-docker.pkg.dev/project-525a47ad-8a94-41ce-85d/docker-node-app/docker-node-app
